# Python version
target-version = "py313"

# Line length
line-length = 88

# Enable pycodestyle (E) and Pyflakes (F) codes by default
[lint]
select = ["E", "F", "W", "I", "N", "B", "A", "C4", "T20"]

# Never enforce these rules
ignore = [
    "E501",  # Line too long (handled by formatter)
    "T201",  # Print statements allowed
]

# Exclude paths
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".ruff_cache",
]

[lint.isort]
known-first-party = ["src"]
force-single-line = true